//
//  AgentGate.swift
//  BoringNotchXPCHelper
//
//  Installs and runs the PreToolUse hook that stands between the agent and your
//  Mac. The DECISION lives in GateDecision.swift, which is pure and tested;
//  this file is only the plumbing around it — writing the hook, reading stdin,
//  asking the user, logging.
//
//  The hook used to be a ~100 line bash script emitted as a Swift string
//  literal, which meant the security logic could only be tested by regenerating
//  the script and shelling out to it. It is now four lines that hand the
//  command to this binary. There is one implementation of the decision and no
//  way for the script on disk to drift from the code that reasons about it.
//
//  That matters more than it sounds: twice the gate was correct in source and
//  not actually in the execution path.
//

import Foundation

enum AgentGate {

    static var directory: URL {
        let url = URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent("Library/Application Support/Brow/agent", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    /// Config lives on a space-free path.
    ///
    /// The hook never fired while settings.json sat under "Application
    /// Support"; the one configuration that provably worked used a plain path.
    /// A space in the settings path is the most likely reason the hook config
    /// was silently not loaded, so keep gate.sh and settings.json out of it.
    static var configDirectory: URL {
        let url = URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent(".brow", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    static var scriptURL: URL { configDirectory.appendingPathComponent("gate.sh") }
    static var settingsURL: URL { configDirectory.appendingPathComponent("settings.json") }
    /// Logs stay put so existing history is not orphaned.
    static var logURL: URL { directory.appendingPathComponent("gate.log") }

    /// The flag that turns this binary into the hook instead of an XPC service.
    static let hookFlag = "--gate-decide"

    /// Writes the hook and exits. For repairing or testing the gate without
    /// having to speak to the agent first.
    static let installFlag = "--install-gate"

    /// Seconds the confirm dialog waits before denying on its own.
    private static let confirmTimeout = 40

    // MARK: - Install

    /// Writes gate.sh and settings.json. Cheap and idempotent; called per run so
    /// the gate cannot drift from the binary that relies on it.
    static func install() {
        let script = Self.script
        if (try? String(contentsOf: scriptURL, encoding: .utf8)) != script {
            try? script.write(to: scriptURL, atomically: true, encoding: .utf8)
        }
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o700], ofItemAtPath: scriptURL.path)

        let settings = """
        {"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"\(scriptURL.path)","timeout":\(confirmTimeout + 15)}]}]}}
        """
        if (try? String(contentsOf: settingsURL, encoding: .utf8)) != settings {
            try? settings.write(to: settingsURL, atomically: true, encoding: .utf8)
        }
    }

    /// The hook script. It no longer decides anything — it forwards stdin to
    /// this binary and lets it answer.
    ///
    /// `exec` so no extra shell process lingers, and an absolute path to the
    /// helper because the hook runs with whatever environment the CLI had.
    /// If the binary is missing the script denies, rather than failing open.
    private static var script: String {
        let helper = Bundle.main.executablePath ?? CommandLine.arguments[0]
        return """
        #!/bin/bash
        # Brow agent gate. Generated by AgentGate.swift — edits are overwritten.
        # The decision lives in GateDecision.swift. This only carries stdin to it.
        HELPER="\(helper)"
        [ -x "$HELPER" ] || { printf '%s' '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Brow gate binary missing."}}'; exit 0; }
        exec "$HELPER" \(hookFlag)
        """
    }

    // MARK: - Run as the hook

    /// Reads a PreToolUse payload on stdin, prints a decision on stdout.
    /// Never returns — it exits the process.
    static func runAsHook() -> Never {
        let input = FileHandle.standardInput.readDataToEndOfFile()
        let command = parseCommand(from: input)

        var (decision, message) = AgentGateDecider.decide(command: command ?? "")

        // A command needing approval is the only path that touches the user.
        // Approval is a click. Never wire this to speech: audio in the room
        // must not be able to approve a command spoken into the same room.
        if case .confirm = decision {
            let approved = askUser(about: command ?? "")
            decision = approved
                ? .allow(reason: "user-approved")
                : .deny(reason: "user-denied")
            message = approved
                ? "Approved by the user."
                : "Denied by the user (or the prompt timed out)."
        }

        log(decision: decision, command: command ?? "")
        emit(decision: decision, message: message)
        exit(0)
    }

    private static func parseCommand(from data: Data) -> String? {
        guard
            let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
            let input = root["tool_input"] as? [String: Any],
            let command = input["command"] as? String,
            !command.isEmpty
        else { return nil }
        return command
    }

    private static func emit(decision: GateDecision, message: String) {
        let payload: [String: Any] = [
            "hookSpecificOutput": [
                "hookEventName": "PreToolUse",
                "permissionDecision": decision.wireValue,
                "permissionDecisionReason": message,
            ]
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: payload) else {
            // Fail closed: an unprintable decision must not read as approval.
            FileHandle.standardOutput.write(Data(
                #"{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Brow could not encode a decision."}}"#.utf8))
            return
        }
        FileHandle.standardOutput.write(data)
    }

    /// Records WHY, not just what: an auto-approved read-only command and one
    /// the user clicked through look identical afterwards otherwise.
    private static func log(decision: GateDecision, command: String) {
        let stamp = ISO8601DateFormatter().string(from: Date())
        let line = "\(stamp)\t\(decision.wireValue)\t\(decision.tag)\t\(command)\n"
        if let handle = try? FileHandle(forWritingTo: logURL) {
            defer { try? handle.close() }
            _ = try? handle.seekToEnd()
            try? handle.write(contentsOf: Data(line.utf8))
        } else {
            try? line.write(to: logURL, atomically: true, encoding: .utf8)
        }
    }

    // MARK: - Screening a command for the in-app agent loop

    /// Screens one command for the BYOK agent loop, which owns its own
    /// conversation and so never goes through the CLI's PreToolUse hook.
    ///
    /// Same decision, same order, same dialog as `runAsHook` -- both call
    /// `AgentGateDecider.decide`, because two paths to a shell must not be able
    /// to disagree about what is safe. The CLI path exists as long as anyone
    /// still uses it; this one is what replaces it.
    ///
    /// Returns nil when the command may run, or the refusal to show the model.
    static func screen(command: String) -> String? {
        let (decision, message) = AgentGateDecider.decide(command: command)

        switch decision {
        case .allow:
            log(decision: decision, command: command)
            return nil

        case .deny:
            log(decision: decision, command: command)
            return message

        case .confirm:
            let approved = askUser(about: command)
            let resolved: GateDecision = approved
                ? .allow(reason: "user-approved")
                : .deny(reason: "user-denied")
            log(decision: resolved, command: command)
            return approved ? nil : "Denied by the user (or the prompt timed out)."
        }
    }

    private static func askUser(about command: String) -> Bool {
        let shown = String(command.prefix(400)).replacingOccurrences(of: "\"", with: "\\\"")
        let source = """
        with timeout of \(confirmTimeout + 5) seconds
          tell application "System Events"
            activate
            set r to display dialog "Jarvis wants to run:" & return & return & "\(shown)" default button "Deny" buttons {"Deny", "Allow once"} with title "Brow — approve command?" with icon caution giving up after \(confirmTimeout)
            if button returned of r is "Allow once" then
              return "allow"
            else
              return "deny"
            end if
          end tell
        end timeout
        """

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        process.arguments = ["-e", source]
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice

        do { try process.run() } catch { return false }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()

        // Anything other than an explicit "allow" — a timeout, a crash, a
        // dismissed dialog — is a denial.
        let answer = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return answer == "allow"
    }
}
