//
//  AgentGate.swift
//  BoringNotchXPCHelper
//
//  Materialises the PreToolUse hook that stands between the agent and your Mac.
//
//  The agent runs with `--tools Bash`, so Bash is its only built-in tool. Every
//  Bash command passes through gate.sh before it can run — this hook is now the
//  only thing between a spoken sentence and a shell, so treat changes here with
//  the care that implies.
//
//  gate.sh decides in three steps, and the ORDER matters:
//    1. deny-list  — refused outright, never prompts
//    2. allow-list — read-only commands, run without prompting
//    3. anything else — asks the user, and a timeout or any error means DENY
//
//  Default-deny is the point. Pattern matching on shell strings is leaky, so
//  the patterns are a backstop; the prompt is the actual control. A command
//  that matches nothing is not assumed safe.
//

import Foundation

enum AgentGate {

    static var directory: URL {
        let url = URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent("Library/Application Support/Brow/agent", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    /// Config lives on a space-free path.
    ///
    /// The hook never fired while settings.json sat under "Application
    /// Support"; the one configuration that provably worked used a plain path.
    /// A space in the settings path is the most likely reason the hook config
    /// was silently not loaded, so keep gate.sh and settings.json out of it.
    static var configDirectory: URL {
        let url = URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent(".brow", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    static var scriptURL: URL { configDirectory.appendingPathComponent("gate.sh") }
    static var settingsURL: URL { configDirectory.appendingPathComponent("settings.json") }
    /// Logs stay put so existing history is not orphaned.
    static var logURL: URL { directory.appendingPathComponent("gate.log") }

    /// Seconds the confirm dialog waits before denying on its own.
    private static let confirmTimeout = 40

    /// Writes gate.sh and settings.json. Cheap and idempotent; called per run so
    /// the gate cannot drift from the binary that relies on it.
    static func install() {
        let script = Self.script
        if (try? String(contentsOf: scriptURL, encoding: .utf8)) != script {
            try? script.write(to: scriptURL, atomically: true, encoding: .utf8)
        }
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o700], ofItemAtPath: scriptURL.path)

        let settings = """
        {"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"\(scriptURL.path)","timeout":\(confirmTimeout + 15)}]}]}}
        """
        if (try? String(contentsOf: settingsURL, encoding: .utf8)) != settings {
            try? settings.write(to: settingsURL, atomically: true, encoding: .utf8)
        }
    }

    private static var script: String {
        """
        #!/bin/bash
        # Brow agent gate. Generated by AgentGate.swift — edits are overwritten.
        # stdin: PreToolUse JSON. stdout: a permission decision.
        # Default is DENY: anything not explicitly allowed must be confirmed by a
        # person, and any failure path denies.

        LOG="\(logURL.path)"
        TIMEOUT=\(confirmTimeout)

        input=$(cat)
        cmd=$(/usr/bin/osascript -l JavaScript -e 'var s=$.NSString.alloc.initWithDataEncoding($.NSFileHandle.fileHandleWithStandardInput.readDataToEndOfFile,4).js; try{JSON.parse(s).tool_input.command}catch(e){""}' <<<"$input" 2>/dev/null)

        # Record WHY, not just what: an auto-approved read-only command and one
        # the user clicked through look identical otherwise.
        log() { printf '%s\\t%s\\t%s\\t%s\\n' "$(date -u +%FT%TZ)" "$1" "$2" "$3" >>"$LOG"; }

        decide() { # $1 = allow|deny, $2 = reason, $3 = short source tag
          log "$1" "${3:-unknown}" "$cmd"
          /bin/cat <<JSON
        {"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"$1","permissionDecisionReason":"$2"}}
        JSON
          exit 0
        }

        [ -z "$cmd" ] && decide deny "Brow could not read the command." unparseable

        # ---- 0. one line only ------------------------------------------------
        # grep matches line by line, so a multi-line command could satisfy the
        # allow-list on its first line while carrying anything on the next:
        #     ls\\nrm -rf ~
        # has no shell metacharacters on any line and starts with "ls". Reject
        # multi-line and control characters outright, before any allow decision.
        case "$cmd" in
          *$'\\n'*|*$'\\r'*|*$'\\t'*)
            decide deny "Brow only runs single-line commands. Ask for one short command." multiline
            ;;
        esac

        # ---- 1. deny-list: never runs, never prompts -------------------------
        # These are extended regexes, so | is ALTERNATION and . is ANY CHARACTER.
        # Both must be escaped when a literal is meant. Getting this wrong is not
        # a harmless over-block: 'curl.*|.*sh' reads as "curl anything" OR
        # "anything containing sh", which denied git push, cat ~/.zshrc and any
        # command mentioning a Screenshot.
        deny_patterns=(
          '(^|[^[:alnum:]])(sudo|doas|su)[[:space:]]'
          'rm[[:space:]]+-[rRfd]+[[:space:]]+/([[:space:]]|$)'
          'mkfs' 'diskutil[[:space:]]+erase' 'dd[[:space:]]+(if|of)='
          ':[[:space:]]*\\(\\)[[:space:]]*\\{'
          '(^|[^[:alnum:]])(shutdown|reboot|halt)([[:space:]]|$)'
          'csrutil' 'spctl' 'tccutil' 'nvram' 'launchctl'
          '(^|[^[:alnum:]])security[[:space:]]' 'keychain'
          '\\.ssh' '\\.aws' '\\.gnupg' '\\.config/gh' 'id_rsa' 'id_ed25519'
          'credentials\\.json' '\\.env([[:space:]]|$|/)'
          '(curl|wget)[^|]*\\|[[:space:]]*(ba|z|k)?sh'
          'git[[:space:]]+push[[:space:]]+(--force|-f)' 'git[[:space:]]+reset[[:space:]]+--hard'
          'chmod[[:space:]]+-R' 'chown[[:space:]]+-R' 'chflags[[:space:]]+-R'
          'defaults[[:space:]]+write' 'pmset[[:space:]]+-a' 'systemsetup'
          'osascript.*do[[:space:]]+shell[[:space:]]+script'
        )
        for p in "${deny_patterns[@]}"; do
          if printf '%s' "$cmd" | /usr/bin/grep -Eqi -- "$p"; then
            decide deny "Blocked by Brow: matches a forbidden pattern. Tell the user to run it themselves." denylist
          fi
        done

        # ---- 2. allow-list: read-only, runs without prompting ---------------
        # Anchored at the start and rejected outright if they chain into
        # anything else, so "ls; rm -rf ~" cannot ride in on "ls".
        # Globs are metacharacters too. Without them, `cat ~/.claude/.credential*`
        # sails past a deny-list that only knows the literal filename, and the
        # auto-allow branch prints an OAuth token with no prompt. Verified live.
        if printf '%s' "$cmd" | /usr/bin/grep -Eq '[;&|><`$()*?{}!~\\[\\]]'; then
          :   # shell metacharacters — skip the allow-list, go to confirm
        else
          allow_patterns=(
            '^(ls|pwd|whoami|hostname|date|uptime|df|du|uname|id|groups)( |$)'
            '^(ps|top -l 1|pgrep)( |$)'
            '^(echo|printf) '
            '^(which|type|command -v) '
            '^git (status|log|diff|branch|show|remote)( |$)'
            '^(defaults read|pmset -g|system_profiler|sw_vers)( |$)'
          )
          # Deliberately NOT auto-allowed:
          #   cat/head/tail/wc/file/stat — these read ARBITRARY FILES. Read-only
          #              is not the same as safe: the secrets on this machine are
          #              files, so an unprompted file read is the whole threat.
          #              A deny-list of known secret paths cannot cover this —
          #              it lost to a single "*". Every file read now confirms.
          #   lsof -i  — enumerates network connections.
          #   open -a  — launches apps, and `open -a Terminal script.sh` or
          #              `open file.command` executes code. State-changing.
          #   say      — `say -o file` writes to disk.
          # The local intent matcher already handles "open chrome" without the
          # agent, so nothing useful is lost by making these confirm.
          for p in "${allow_patterns[@]}"; do
            if printf '%s' "$cmd" | /usr/bin/grep -Eq -- "$p"; then
              decide allow "Read-only command, auto-approved by Brow." autoallow
            fi
          done
        fi

        # ---- 3. everything else: ask a person -------------------------------
        # Approval is a click. Never wire this to speech: audio in the room must
        # not be able to approve a command.
        short=$(printf '%s' "$cmd" | /usr/bin/head -c 400 | /usr/bin/sed 's/"/\\\\"/g')
        answer=$(/usr/bin/osascript <<APPLESCRIPT 2>/dev/null
        with timeout of $((TIMEOUT + 5)) seconds
          tell application "System Events"
            activate
            set r to display dialog "Jarvis wants to run:" & return & return & "$short" default button "Deny" buttons {"Deny", "Allow once"} with title "Brow — approve command?" with icon caution giving up after $TIMEOUT
            if button returned of r is "Allow once" then
              return "allow"
            else
              return "deny"
            end if
          end tell
        end timeout
        APPLESCRIPT
        )

        if [ "$answer" = "allow" ]; then
          decide allow "Approved by the user." user-approved
        fi
        decide deny "Denied by the user (or the prompt timed out)." user-denied
        """
    }
}
